services:
   appsmith:
     image: index.docker.io/appsmith/appsmith-ee
     container_name: appsmith
     ports:
         - "80:80"
         - "443:443"
     volumes:
         - ./stacks:/appsmith-stacks
     environment:
         - APPSMITH_MONGODB_URI=mongodb://localhost:27017/appsmith
         - APPSMITH_REDIS_URL=redis://localhost:6379
         - APPSMITH_POSTGRES_HOST=localhost
     restart: unless-stopped